//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILABDb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arkivalie
    {
        public int ArkivalieID { get; set; }
        public string Journal { get; set; }
        public string Arkivfondnr { get; set; }
        public string Art { get; set; }
        public string KasseNr { get; set; }
        public string Signatur { get; set; }
        public bool Klausul { get; set; }
        public Nullable<double> YderAarStart { get; set; }
        public Nullable<double> YderAarSlut { get; set; }
        public string Omfang { get; set; }
        public Nullable<double> AntKort { get; set; }
        public string Indlevering { get; set; }
        public string Note { get; set; }
    }
}
