//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILABDb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bibliotek
    {
        public int BogID { get; set; }
        public string Bogkode { get; set; }
        public string Journal { get; set; }
        public string DK5 { get; set; }
        public string Ordningsord { get; set; }
        public string Titel { get; set; }
        public string Undertitel { get; set; }
        public string Redaktor { get; set; }
        public string Forfatter { get; set; }
        public Nullable<double> Udgivet { get; set; }
        public string Forlag { get; set; }
        public string Samlemappe { get; set; }
        public string Indlevering { get; set; }
        public string Note { get; set; }
    }
}
