//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILABDb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billeder
    {
        public int BilledID { get; set; }
        public string Journal { get; set; }
        public string Billedindex { get; set; }
        public string Numordning { get; set; }
        public string Ordning { get; set; }
        public string CDnr { get; set; }
        public string Fotograf { get; set; }
        public string Format { get; set; }
        public Nullable<double> Materiale { get; set; }
        public string Placering { get; set; }
        public bool Ophavsret { get; set; }
        public bool Klausul { get; set; }
        public Nullable<System.DateTime> Datering { get; set; }
        public string Indlevering { get; set; }
        public string Note { get; set; }
    }
}
