//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILABDb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public int EventID { get; set; }
        public Nullable<double> PersonID { get; set; }
        public Nullable<double> Ind_Dag { get; set; }
        public Nullable<double> Ind_Mrd { get; set; }
        public Nullable<double> Ind_Aar { get; set; }
        public string Eventkode { get; set; }
        public string InstKode { get; set; }
        public string Tekstfelt1 { get; set; }
        public string Tekstfelt2 { get; set; }
        public string Tekstfelt3 { get; set; }
        public string Tekstfelt4 { get; set; }
        public string Tekstfelt5 { get; set; }
        public string Tekstfelt6 { get; set; }
        public string Tekstfelt7 { get; set; }
        public string Tekstfelt8 { get; set; }
        public string Tekstfelt9 { get; set; }
        public string Tekstfelt10 { get; set; }
        public string Note { get; set; }
    }
}
