//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILABDb.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ILABClassic : DbContext, IDisposable
    {
        public ILABClassic()
            : base("name=ILABClassic")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArkfondTypes> ArkfondTypes { get; set; }
        public virtual DbSet<Arkivalie> Arkivalie { get; set; }
        public virtual DbSet<ArkivFond> ArkivFond { get; set; }
        public virtual DbSet<Aviser> Aviser { get; set; }
        public virtual DbSet<Bibliotek> Bibliotek { get; set; }
        public virtual DbSet<Billeder> Billeder { get; set; }
        public virtual DbSet<EventKoder> EventKoder { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<Giver> Giver { get; set; }
        public virtual DbSet<institution> institution { get; set; }
        public virtual DbSet<Journaler> Journaler { get; set; }
        public virtual DbSet<Kirkebog> Kirkebog { get; set; }
        public virtual DbSet<Kopi_af_ArkivFond> Kopi_af_ArkivFond { get; set; }
        public virtual DbSet<Kort> Kort { get; set; }
        public virtual DbSet<MatrikelSted> MatrikelSted { get; set; }
        public virtual DbSet<Matrikler> Matrikler { get; set; }
        public virtual DbSet<Personer> Personer { get; set; }
        public virtual DbSet<Sekvenser> Sekvenser { get; set; }
        public virtual DbSet<udklip> udklip { get; set; }
        public virtual DbSet<UserTbl> UserTbl { get; set; }
    }
}
