//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILABDb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class institution
    {
        public int InstID { get; set; }
        public string InstKode { get; set; }
        public string Navn { get; set; }
        public string Gade { get; set; }
        public string Nr { get; set; }
        public string Sted { get; set; }
        public string Postnr { get; set; }
        public Nullable<System.DateTime> Stiftet { get; set; }
        public Nullable<System.DateTime> Afsluttet { get; set; }
        public string Note { get; set; }
    }
}
