//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILABDb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kirkebog
    {
        public int PersonID { get; set; }
        public string Fornavn { get; set; }
        public string Efternavn { get; set; }
        public string Ind_dato { get; set; }
        public string Kirkehandling { get; set; }
    }
}
