//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILABDb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kort
    {
        public int KortID { get; set; }
        public string Kortnr { get; set; }
        public string Journal { get; set; }
        public string Navn { get; set; }
        public string KortType { get; set; }
        public string Propertion { get; set; }
        public string Udgiver { get; set; }
        public Nullable<int> DateringAar { get; set; }
        public Nullable<int> RevAar { get; set; }
        public string Omraade { get; set; }
        public string Depot { get; set; }
        public string Format { get; set; }
        public string Materiale { get; set; }
        public string Indlevering { get; set; }
        public string Note { get; set; }
    }
}
