//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILABDb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matrikler
    {
        public int MatrikelID { get; set; }
        public string MatrikelNr { get; set; }
        public string Kilde { get; set; }
        public string Oprettet { get; set; }
        public string Dato { get; set; }
        public string Stamnr { get; set; }
        public string Ejer { get; set; }
        public string Bruger { get; set; }
        public string Vejnavn { get; set; }
        public string Vejnr { get; set; }
        public string Sted { get; set; }
        public string Postnr { get; set; }
        public string By { get; set; }
        public string Note { get; set; }
    }
}
