//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILABDb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personer
    {
        public int PersonID { get; set; }
        public string Fornavn { get; set; }
        public string Mellemnavn { get; set; }
        public string Pigenavn { get; set; }
        public string Efternavn { get; set; }
        public Nullable<double> Ind_Dag { get; set; }
        public Nullable<double> Ind_Mrd { get; set; }
        public Nullable<double> Ind_Aar { get; set; }
        public string Adresse_Vej { get; set; }
        public string Adresse_nr { get; set; }
        public string Adresse_Sted { get; set; }
        public string Adresse_Postnr { get; set; }
        public string Adresse_PostBy { get; set; }
        public string Note { get; set; }
    }
}
