//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILABDb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sekvenser
    {
        public int SekvensID { get; set; }
        public string SekvensNr { get; set; }
        public string Journal { get; set; }
        public string Titel { get; set; }
        public Nullable<double> DateringDag { get; set; }
        public Nullable<double> DateringMrd { get; set; }
        public Nullable<double> DateringAar { get; set; }
        public string Kilde { get; set; }
        public string Interviewer { get; set; }
        public bool Klausul { get; set; }
        public string Type { get; set; }
        public string Indlevering { get; set; }
        public string Note { get; set; }
    }
}
