//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILABDb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class udklip
    {
        public int UdklipsID { get; set; }
        public string Mappe { get; set; }
        public string Overskrift { get; set; }
        public string Datering { get; set; }
        public string Aviskode { get; set; }
        public string Note { get; set; }
    }
}
