//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archives
    {
        public int ArchiveId { get; set; }
        public string ArchiveNb { get; set; }
        public string Title { get; set; }
        public string Definition { get; set; }
        public int ArchiveType { get; set; }
        public Nullable<System.DateTime> Established { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public string Comment { get; set; }
    }
}
