//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int BookId { get; set; }
        public string BookCode { get; set; }
        public string DK5 { get; set; }
        public string Tag { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string Author { get; set; }
        public string Editor { get; set; }
        public int PublishYear { get; set; }
        public string Attache { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Journal_JournalId { get; set; }
    
        public virtual Journals Journals { get; set; }
    }
}
