//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cadasters
    {
        public int CadasterId { get; set; }
        public string CadasterNb { get; set; }
        public string Source { get; set; }
        public int CreatedYear { get; set; }
        public int Year { get; set; }
        public string StamNr { get; set; }
        public string User { get; set; }
        public string Street { get; set; }
        public string Number { get; set; }
        public string Area { get; set; }
        public int ZipNumber { get; set; }
        public string City { get; set; }
        public string Comment { get; set; }
    }
}
