//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChirchRecords
    {
        public int ChirchRecordId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Event { get; set; }
        public System.DateTime Date { get; set; }
        public int PersonId { get; set; }
    }
}
