//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maps
    {
        public int MapId { get; set; }
        public string MapNb { get; set; }
        public string Title { get; set; }
        public int MapType { get; set; }
        public string Proportion { get; set; }
        public string Publisher { get; set; }
        public int PublishYear { get; set; }
        public int RevisionYear { get; set; }
        public string Area { get; set; }
        public string Format { get; set; }
        public int Material { get; set; }
        public string Depot { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Journal_JournalId { get; set; }
    
        public virtual Journals Journals { get; set; }
    }
}
