//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MuninDbEntities : DbContext
    {
        public MuninDbEntities()
            : base("name=MuninDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Archives> Archives { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Cadasters> Cadasters { get; set; }
        public virtual DbSet<ChirchRecords> ChirchRecords { get; set; }
        public virtual DbSet<Clips> Clips { get; set; }
        public virtual DbSet<Journals> Journals { get; set; }
        public virtual DbSet<Maps> Maps { get; set; }
        public virtual DbSet<Pictures> Pictures { get; set; }
        public virtual DbSet<Providers> Providers { get; set; }
        public virtual DbSet<Sequences> Sequences { get; set; }
    }
}
