//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pictures
    {
        public int PictureId { get; set; }
        public string PictureIndex { get; set; }
        public string OrderNum { get; set; }
        public string Tag { get; set; }
        public string CDNb { get; set; }
        public string Photograph { get; set; }
        public string Size { get; set; }
        public int PictureMaterial { get; set; }
        public bool Copyright { get; set; }
        public bool Provision { get; set; }
        public string Placed { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Journal_JournalId { get; set; }
    
        public virtual Journals Journals { get; set; }
    }
}
