//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Providers
    {
        public int ProviderId { get; set; }
        public string Name { get; set; }
        public string Att { get; set; }
        public string Address { get; set; }
        public int ZipCode { get; set; }
        public string City { get; set; }
        public System.DateTime Registrated { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Journal_JournalId { get; set; }
    
        public virtual Journals Journals { get; set; }
    }
}
