//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sequences
    {
        public int SequenceId { get; set; }
        public string SequenceNb { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Source { get; set; }
        public string Interviewer { get; set; }
        public bool Copyright { get; set; }
        public int SequenceType { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Journal_JournalId { get; set; }
    
        public virtual Journals Journals { get; set; }
    }
}
